server:
  port: 8081
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource

