server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: xzcd1993
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 30000
      max-lifetime: 14400000
  jpa:
    hibernate:
#      ddl-auto: update create
      ddl-auto: update
    show-sql: true
#  security:
#    user:
#      name: user
#      password: password
cxf:
  path: /services
management:
  server:
    address: 127.0.0.1
    port: 8088
  endpoints:
    web:
      base-path: /
      exposure:
        exclude: env
#        include: ["health","info"]
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always


info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"